[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "https://sozu.io"
version = "1.1.0-rc.0"
license = "AGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2021"
rust-version = "1.74.0"
include = ["README.md", "Cargo.toml", "src/**/*"]

[dependencies]
clap = { version = "^4.5.4", features = ["derive"] }
jemallocator = { version = "^0.5.4", optional = true }
libc = "^0.2.155"
log = "^0.4.21"
mio = { version = "^1.0.0", features = ["os-poll", "net"] }
nix = { version = "^0.29.0", features = ["signal", "fs"] }
nom = "^7.1.3"
paw = "^1.0.0"
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = "^1.0.117"
prost = "^0.13.1"
tempfile = "^3.10.1"
termion = "^4.0.0"
thiserror = "^1.0.61"

sozu-command-lib = { path = "../command", version = "^1.1.0-rc.0" }
sozu-lib = { path = "../lib", version = "1.1.0-rc.0" }

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.16.0"

[features]
default = ["jemallocator"]
unstable = []
logs-debug = ["sozu-lib/logs-debug", "sozu-command-lib/logs-debug"]
logs-trace = ["sozu-lib/logs-trace", "sozu-command-lib/logs-trace"]
tolerant-http1-parser = ["sozu-lib/tolerant-http1-parser"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
